### ISSUE TITLE
CSS background without data-bg

### ISSUE THREAD

**Issue by bomastudioweb** [verlok/vanilla-lazyload#491]
I like vanilla-lazyload and I would like to use it as extensivelly as possible.

In regard to the support for **CSS background**:
Could the script work if we specify the url of the image only in the CSS?

*Images* are specified in the HTML so it seems straightforward to let the mechanism of the script rely on the attribute (which is in the HTML itself)

*CSS backgrounds* I have two cases:

1) image URL specified in the HTML (style attribute) => data-bg attribute is OK!
1) image URL specified in the CSS => could the script work without specifing a data-bg attribute? What if we leave it empty?

This way we can fully control CSS-backgrounds (with a great fallback) in a CSS-only way:

HTML
`<div class="banner lazy">`

CSS
```
.banner  { ... }
.banner.loaded, .no-js .banner { ... }
```

Does this make sense?

**Comment by bomastudioweb** [comment]
I tried to obtain some effectv relying on the "data-was-processed" value, which is apparently deprecated since 
Version 17. I'd love some feedback on this

1) Could this "add css class only" approach work? (I was inspired by https://web.dev/lazy-loading-images/)

2) What value of "data-ll-status" could I use to replace data-was-processed="true"?

3) Is there any chance to get this "behaviour" working for vanilla-lazyload? Or would it "break things" so much in the current implementation? I imagine that you rely on the presence and correctness of "data-bg" attribute to make it work...


.banner  { ... }
.banner[data-was-processed=true] { APPLY BACKGROUND }

**Comment by bomastudioweb** [comment]
After updating vanilla-lazyload to the latest version, I found that the "CSS-only approach" works; it relies on 
data-ll-status="entered" attribute value.

HTML
<div class="banner lazy">

CSS
.banner { ...your CSS rules... }
.banner [data-ll-status=entered], .no-js .banner { background:url(''); }

If this is the right way to do it, could you consider expliciting it in the documentation?
Thx @verlok

**Comment by verlok** [comment]
Hey @bomastudioweb ,
sorry for the very late reply!

I can see you've found a solution, after a couple of days!
Yes that works, but I wouldn't rely on the `data-ll-status` attribute, because it's meant to be an attribute used by my script itself, and it could change in the future.

A much more solid solution would be to use the `callback_entered` callback to set a `visible` class in your DOM element, exactly like it's suggested on [the web.dev article you mentioned](https://web.dev/lazy-loading-images/).

So you'd do:

```js
new LazyLoad({
  "callback_enter": el => el.classList.add("visible")
});
```

or, in ES5

```js
new LazyLoad({
  "callback_enter": function(el) {
    el.classList.add("visible")
  }
});
```

Then you'd apply your CSS background image only to the `.visible` elements.

What do you think?

**Comment by bomastudioweb** [comment]
Hi @verlok ,

that sounds like a pretty good solution.

Would you see it as an improvement for your script to have a way that provide this behaviour out of the box, as a fundamental part of the job, without adding any JS at all? Just asking...

**Comment by verlok** [comment]
Hey @bomastudioweb 

> Would you see it as an improvement for your script to have a way that provide this behaviour out of the box, as a fundamental part of the job, without adding any JS at all? Just asking...

Not sure, because the usage you propose is a very specific corner case I guess. I can only guess, but I think the vast majority of the users use vanilla-lazyload on regular `img` images, `iframe`s, `video`s, and inline background images. 

On the other side, to implement "lazy CSS backgrounds" on the user side costs very few lines of code.
The code you proposed and I report below already works today without any change.

```js
// LAZY IMG
var LazyImg = new LazyLoad({
	elements_selector: ".lazy",
	callback_finish: function (element) {
		window.finish = 1;
	}
});

// LAZY CSS BACKGROUNDS
var LazyBg = new LazyLoad({
	elements_selector: ".lazy-background",
	callback_enter: function(element) {
		element.classList.add("visible")
	}
});
```

**Comment by verlok** [comment]
I'm closing this for now. Feel free to reopen if you need any more information.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.
Thank you for thinking about it. 

Have a nice day!

**Comment by bomastudioweb** [comment]
Thank you for your replies. Though this recipe is very easy to cook, I disagree it's a very specific case. 

See [this](http://campodipapi.bomatest.eu/it) example (still a WIP)
This is the perfect use case for background images in CSS: we need decorative (not essential) images as backgrounds of some banners. These are merely for creating an atmosphere on the website, we use `<img>` tag for essential images (products, recipes, etc.). We think CSS is the perfect place for "storing" these images as it's a part of the style layer and it doesn't influence the content (markup). 

Just my 2cents... Thank you for your software and your support!

**Comment by verlok** [comment]
Ciao @bomastudioweb, 
yes you're right, CSS is the right place to store those background images' URLs, and LazyLoad is the perfect way to reveal it.

I've seen the websited you linked (btw, it's beautiful) and yes, you convinced me.
I'm thinking of adding an option to make LazyLoad apply a class to the elements that entered the viewport. Something like `class_entered`. 

So instead of using

```css
.banner-agente[data-ll-status=entered] {
  background-image: url('banner-agenti.jpg');
}
```

you would simply do

```css
.banner-agente.entered {
  background-image: url('banner-agenti.jpg');
}
```

What do you think?

PS: Grazie mille per il caffè!

**Comment by verlok** [comment]
Aaaaand, done! 
You got it in version 17.3.0.
That was easy!

**Comment by bomastudioweb** [comment]
I think it's great!
