### ISSUE TITLE
React demo with threshold doesn't work

### ISSUE THREAD

**Issue by meotimdihia** [verlok/vanilla-lazyload#494]
**To Reproduce**
Check code on https://codesandbox.io/s/exciting-christian-ruqe1?file=/src/config/lazyload.js
the threshold is 10000, but images load only when I scroll to the viewport

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version: 17+

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 - Version newest 
![chrome_2020-12-01_21-45-28](https://user-images.githubusercontent.com/300961/100755366-afeadc80-341e-11eb-91cd-2be852a72244.png)

**Comment by verlok** [comment]
Hey @meotimdihia,
thank you for asking.

First of all, the value of `threshold` must be a numeric value and not a string, so you should remove the `"` around it.
Like this:

```js
export default {
  elements_selector: ".lazy",
  threshold: 10000
};
```

Secondly, you might want to test your Codesandbox in a separate window, because if you don't, Codesandbox falses the result.

- [Find here my fork](https://codesandbox.io/s/late-meadow-2mlo8?file=/src/config/lazyload.js:60-65)
- [And the same fork at full screen](https://2mlo8.csb.app/)

You will see all the images were downloaded.

![image](https://user-images.githubusercontent.com/1127721/100801703-a5354500-3428-11eb-9cc6-346b37236d7f.png)

Please let me know if this solves for you.

**Comment by meotimdihia** [comment]
I can't install Vanilla-lazyload in my next.js project. 
with simple lines: 
```javascript
import LazyLoad from "vanilla-lazyload"
const test = new LazyLoad({
  threshold: 10000,
})
```
I got the bug:
```javascript
TypeError: Cannot read property 'querySelectorAll' of null
    at et (C:\sources\example\node_modules\vanilla-lazyload\dist\lazyload.min.js:1:5969)
```

**Comment by verlok** [comment]
Your latest message is related to a completely different issue. Will you be able to open another issue here on github please?

**Comment by verlok** [comment]
Did my answer about threshold solve the initial issue for you?

**Comment by meotimdihia** [comment]
Sorry, I install it to test on my web. All other libraries can't work in my case, too.
I ended up writing custom lazy loading with IntersectionObserver API.
I close this issue.

**Comment by verlok** [comment]
It's just a missing check to make it work on the server-side. 

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 
Have a nice day!
