### ISSUE TITLE
Not working on ISO 14.3 Safari

### ISSUE THREAD

**Issue by ahmadzissa** [verlok/vanilla-lazyload#498]
Hello, the code was working without any issue  but after  the new  ISO  update it stopped working on  MAC and IPhone 

I tried it on ISO  14.3 Safari  Browser 

it doesn't work on all iPhones  with ISO 14.3

**Comment by verlok** [comment]
I've just tried [this demo](https://www.andreaverlicchi.eu/vanilla-lazyload/demos/image_basic.html) on iOS 14.3 and I didn't find any issues. 

If you could provide more information about your use case, I might be able to help you solve this issue. 

Thanks
Andrea

**Comment by ahmadzissa** [comment]
Thank you very much   maybe  it stopped on safari because the content is loaded using ajax request  not normally with browser load    

see this example store you will find the images at the bottom 

 [https://aliexpressreviewstest4.myshopify.com/products/brand-2018-cardigan-multi-button-hoodies-men-fashion-tracksuit-male-sweatshirt-mens-purpose-tour-4xl#az_reviews](url)

and here is the code I'm using 

  ```
 <script>
   


        jQuery(document).ready(function (){

            new LazyLoad({
                class_applied: "lz-applied",
                class_loading: "lz-loading",
                class_loaded: "lz-loaded",
                class_error: "lz-error",
                class_entered: "lz-entered",
                class_exited: "lz-exited",

            });
        });

    </script>
```

**Comment by verlok** [comment]
Hey there,

the fact that your solution is not working anymore in the newer versions of Safari is probably because in that browser, the `ready` event of jQuery arrives in a different moment, probably too early. Try to instantiate the `LazyLoad` object later in time.

In addition, please remind that if you update the page content using AJAX as I'm seeing on your website, you need to call the `update()` method on the `LazyLoad` instance, that you'll have stored in a variable.
[Read more about dynamic content](https://github.com/verlok/vanilla-lazyload/blob/master/README.md#dynamic-content).

**Comment by verlok** [comment]
Hey @ahmadzissa,
did my previous comment solve your question?

I'm closing this for now since you didn't reply.
Feel free to reopen if you still need help.
