### ISSUE TITLE
Fade in stops placeholder image from showing

### ISSUE THREAD

**Issue by ashkan-ahmadi** [verlok/vanilla-lazyload#515]
**Describe the bug**
When the fade in CSS is added, the `img.lazy { opacity: 0 }` code blocks the placeholders from displaying. The lazy load and the fade in work smoothly but the placeholder disappears.

**To Reproduce**
Add the following code:
```
<style>
      img.lazy {
        opacity: 0;
      }
      img:not(.initial) {
        transition: opacity 1s;
      }
      img.initial,
      img.loaded,
      img.error {
        opacity: 1;
      }

      img:not([src]) {
        visibility: hidden;
      }
</style>
<img src="PLACEHOLDER.jpg" class="lazy" data-src="IMAGE.jpg">
```

**Expected behavior**

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.3.1

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by verlok** [comment]
Hey @ashkan-ahmadi 

that’s because what LazyLoad is meant to do and does is to replace The `src` attribute with what you put in the `data-src` to start loading the image. 

If you want the fade-in effect to appear above a placeholder image, you should consider different techniques, e.g. using a background image to hold your placeholder. 

Please let me know if this answers your question.

**Comment by verlok** [comment]
Hey @ashkan-ahmadi, I'm closing this for now since you didn't reply.
Feel free to reopen if you still need help.
