### ISSUE TITLE
Video is loaded outside of viewport in Swiper

### ISSUE THREAD

**Issue by DeoThemes** [verlok/vanilla-lazyload#520]
**Is your support request related to a problem? Please describe.**
I'm trying to lazyload videos in Swiper and load them only when user swipes to them. My first slide contains image and second has a video. However when my slider is loaded **lazy entered loaded** classes applied to the video even when the second slide is out of viewport. I can't find where is the issue here, please check my code below.

**To Reproduce**

```JS
let slider = document.querySelector('.eversor-hero-slider');

if ( slider ) {
	var swiper = new Swiper('.eversor-hero-slider', {
		loop: false,
		pagination: {
				el: ".swiper-pagination",
				clickable: true
		}
	});
}

/* LazyLoad */
var lazyLoadInstance = new LazyLoad({
	elements_selector: ".lazy",
});

if (lazyLoadInstance) {
	console.log("our lazy content is ready");
	lazyLoadInstance.update();
}
```

**Expected behavior**
Video should be loaded only when user is swiping

**LazyLoad version**
- Version 17.x.x

**Desktop (please complete the following information):**
Windows 10
Chrome
90.x.x

**Screenshots**
![lazyloaded](https://user-images.githubusercontent.com/16485360/116492992-4b9a4f00-a8d0-11eb-9fbc-a6004f116c77.jpg)

**Comment by verlok** [comment]
Hey @DeoThemes ,
thanks for opening this. 

Couple of questions here:

1) why don’t you use swiper’s native LazyLoad feature instead of trying to make the two libraries work together? https://swiperjs.com/demos#lazy-load-images - Is it because Swiper doesn’t support lazy loading of video? That would be optimal because Swiper does DOM nodes duplications and moving around that could trigger IntersectionObserver and ultimately the lazy loading of the video 
2) I assume the swipe is horizontal, and since the the default `threshold`/`thresholds` options in LazyLoad don’t consider horizontal scroll, but could you please check if the second slide, the one containing the video, is inside the browser’s viewport, even just by 1 pixel? That would trigger the IntersectionObserver and make LazyLoad start loading the lazy video.

**Comment by DeoThemes** [comment]
Yes, the main reason I chose vanila-lazyload is the ability to lazyload videos. I'm also trying to use this codepen as an example - https://codepen.io/DeoThemes/pen/oNBRbqm It works fine in this example, but for some reason it's triggering the video slide on my working demo (I'm using WordPress) - https://arendelle.deothemes.com/

**Comment by DeoThemes** [comment]
Thanks to your #2 question I think I finally found the cause. Since my video is stretched 100% width it is loading on page load, I guess because it's overlapping scroll bar. Swiper's first slide width is 1903px, so the second slide resides just in this remaining 17px spot. I'm not sure if scroll bar considered as viewport though. Adding these properties to the video layer prevents video from loading: **style="position: relative; left: 18px; width: calc(100% - 20px);"** Now I just need to find an elegant way how to smoothly shift if back to the origin when the user scrolls to it :)

**Comment by verlok** [comment]
Hey @DeoThemes,
I’m glad I helped you to solve!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 

Have a nice day!

**Comment by DeoThemes** [comment]
Got you a coffee mate, have a good one :)
