### ISSUE TITLE
How can I lazyload images without using `data-` prefix in `src`

### ISSUE THREAD

**Issue by thelovekesh** [verlok/vanilla-lazyload#522]
In most of the `CMS` solutions, we can see that the content is generated programmatically and due to some limitations we can not change that content inside them. Using lazyload with `data-src` is awesome but I want to know a possible way in which I can lazyload all the images without using `data-` prefix as I can not add it inside a `CMS`.

**Comment by verlok** [comment]
In the moment that the `img` with a `src` attribute gets in the browser, the images will start loading immediately. 

If you can’t change that, you might be interested in using native lazy loading, by adding the `loading="lazy"` attribute to your images and iframes.

That doesn’t have anything to do with this project, since the implementation lays all in the browser, and it works only in browsers that support it, but it’s a quick win to lazy load your images if you can’t do else. 

Let me know what you think.

**Comment by thelovekesh** [comment]
Is this possible that I load the script in the starting of the page and then it stop images to start loading immediately. Just in case it's possible.. something like this can be implemented or not?

**Comment by verlok** [comment]
No it’s not possible, because:

> In the moment that the `img` with a `src` attribute gets in the browser, the images will start loading immediately. 

JavaScript is inevitably loaded after the HTML, so there’s no way to stop that behaviour using javascript. 

If you can’t change your HTML in your CMS, there’s no way to use Javascript-based lazy loading.

**Comment by thelovekesh** [comment]
Completely agree! I have made some edits to the core of the software and it's working now.

**Comment by verlok** [comment]
Hey @thelovekesh, 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 

Have a nice day!
