### ISSUE TITLE
When the image enters the viewport it takes a short time to switch from the small pixelised image to the good one

### ISSUE THREAD

**Issue by romain-granai** [verlok/vanilla-lazyload#529]
So, I'm currently working on a website which is : https://www.amandacharchian.com/

The browser is scrolling automatically, well in fact it's the div that contains the image which is animated, and the animation speed is triggered on scroll.

So I'm using the plugin in it's simpler form:

`<img alt="A lazy image" class="lazy" src="<?php echo $imgSmallUrl; ?>" data-src="<?php echo $imgUrl; ?>" />`

on the data-src is the big image which will replace the src attribute containing the small image, as soon as the image enter in the viewport. However, when the image enter the viewport, for a short time you can still see the small image (pixelised), before it's switched to the big nice image. Is it a bug or something? Here is the Js :

```
var lazyLoadInstance = new LazyLoad({
    // Your custom settings go here
    threshold: 500
});
```

As you can see very simple, although threshold doesn't seem to do anything to fix my problem. (I tried with threshold at 0 and event with a negative value)

The perfect scenario would be to load (switch from small to big), the image which is just after the image that just enter the viewport. So in my case I would have always 2 images loaded. Or another solution would be to switch the next image (the one after the one already displayed), some px before it enter the viewport. And then it would avoid that disgusting change.

That's where I thought 'threshold' could help me, but didn't.

Thank you, I wish I was clear enough, and hope to a have a quick answer.

**Comment by verlok** [comment]
Hey @romain-granai,
thank you for opening this.

The thing is, `threshold` does exactly what you're asking for.
You can also use the `thresholds` option which allows you to specify the threshold values in `%`. 
So you could try with `threshold: "100% 0".

A couple of suggestions, though:
1) don't lazy load the first 2 images. Use eagerly loading there. So instead of doing `<img data-src="some.jpg">` do `<img src="some.jpg">` for the first 2 images.
2) some of your images are not optimized, see the following weights I've found out in the network panel.
3) since your website is full responsive from mobile to desktop, you should really create 2 or 3 scaled versions of the image and serve them according to the display size. These is called "responsive images". You can read more about them in [this blog post](https://www.andreaverlicchi.eu/lazy-load-responsive-images-in-2020-srcset-sizes-picture-webp/), which also talks about how to lazy load them.

![image](https://user-images.githubusercontent.com/1127721/125934527-e96eab6b-8ff6-4715-bcdd-267508aa1c8b.png)

Please let me know how it goes!

**Comment by verlok** [comment]
Hey @romain-granai, 
I’m going to assume you solved so I'm closing this issue.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
