### ISSUE TITLE
Chrome - overflow + negative offset - image does not load

### ISSUE THREAD

**Issue by DusanMilko** [verlok/vanilla-lazyload#534]
Image doesnt load as you scroll to it.

Have image inside element with negative offset like negative margin top, or transform Y.
Have that within an element with overflow hidden. 
Have image below fold.

Image doesn't load as you scroll to it.

https://codepen.io/dusanmilko/pen/BaZWPrg

In this demo second image never loads. remove negative offset or overflow hidden and it works.

**Comment by verlok** [comment]
Hey @DusanMilko,
thank you for opening this.

Please bare in mind that the intersection check is done by browsers themselves, using the IntersectionObserver API.

I've checked your Codpen, and saw that appears to be a CSS problem, because the image is rendered 0x0 pixels.

![image](https://user-images.githubusercontent.com/1127721/132972999-f36f2585-0cd9-4a6c-bfcb-c835c5280977.png)

My proposal is: try and use a width and a height on the image tag [like I did here](https://codepen.io/verlok/pen/ExXmMdm) and you'll see the images appear.

```html
<img 
  data-lazy="" 
  width="351" 
  height="250" 
  data-src="https://contractnetwork.it/wp-content/uploads/2021/05/Copia-di-BARBERSHOP-OWM-01-351x250.jpg">
```

Please let me know if this sounds like a sensible solution to you.

**Comment by verlok** [comment]
@DusanMilko did you have any luck solving this issue?

**Comment by verlok** [comment]
Hey @DusanMilko, 
I’m going to assume you solved so I'm closing this issue.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
