### ISSUE TITLE
Works for Fancybox

### ISSUE THREAD

**Issue by MrMerkin** [verlok/vanilla-lazyload#537]
Just wanted to let you know that lazyLoad works with Fancybox.

Might be good to add this to the Readme so if anyone is searching for lazy loading Fancybox, your page will pop up. I haven't tried all the variants Fancybox uses (galleries, etc), but I'm using the hidden `<div>` method that launches a hidden element on the page with an image in it. Works out of the box since Fancybox uses its own `data-fancybox` attribute there are no conflicts to work around.

Nothing special needed, you just use the `data-src` as your `src` for the `<img>` and set the class to `lazy` or whatever is in your setup, and it just works. When the Fancybox lightbox opens, the image will lazyLoad. 😬

Just wanted to point this out since I didn't see it mentioned in the docs and Fancybox is widely used.

Also, I'm doing this all in WordPress (not that it matters), but it works without a problem. Enqueues fine, preloads with hash integrity and crossorigin link, so there are no delays. 👍🏻

**Comment by verlok** [comment]
Thanks for letting me know. 

It’s good to know that the two libraries work together, but I’m  not sure I will write it in the docs, otherwise I would need to create a list if all other popular scripts this script works along with, and that would be a loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong list. 

After all, this is pure vanilla JavaScript. It works even with React, which is a totally different way of handling the DOM with  JavaScript.
