### ISSUE TITLE
cancel_on_exit not working

### ISSUE THREAD

**Issue by jellohouse** [verlok/vanilla-lazyload#570]
**Describe the bug**
I see in the network tab, that after the component is unmounted (a new page is loaded) the images that have not finished loading from the previous page are still loading.
This makes the new page slow to load as the previous page images are still loading...
The lazy loading (and everything else) works properly.

**To Reproduce**
My Image component:
```js
import LazyLoad from "vanilla-lazyload";

if (!document.lazyLoadInstance) {
  document.lazyLoadInstance = new LazyLoad({
    elements_selector: ".lazyload",
    cancel_on_exit: true
  });
}

function ImageComp(props) {
  useEffect(() => {
    document.lazyLoadInstance.update();
  }, [])

  return(
     <img className="lazyload" data-src={props.src} .... />
  )
}

```

**Expected behavior**
I would expect the images to stop downloading as the propert cancel_on_exit is set to true.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version: 17.8.1

**Desktop (please complete the following information):**
 - OS: Mac OS 12
 - Browser: Firefox

**Comment by verlok** [comment]
Hey @jellohouse,
sorry for not replying before, I got overwhelmed by work.

> I see in the network tab, that after the component is unmounted (a new page is loaded) the images that have not finished loading from the previous page are still loading.

I understand your problem.

The `cancel_on_exit: true` property is meant to cancel the loading of images that exit the viewport while still loading, e.g. if users are fast scrolling on a slow connection.

I wouldn't know why, in the case you described (basically destroying all the DOM and creating a new page using React), the IntersectionObserver doesn't trigger the exit. React has a strange behaviour that most of the times is unknown even to the more experienced web developer.

You could try setting all images `src` attribute to `""` before unmounting `ImageComp`. This would cancel the download of the images that are still downloading, but it probably would also display the broken image icon for some milliseconds, which is not ideal.

Unfortunately, I don't have any better solution to propose.

PS: I will change the label attached to this issue because this is not a bug of this script.

**Comment by jellohouse** [comment]
Hey Verlok! No worries - thanks for the response.

Yes it's strange that IntersectionObserver doesn't trigger the exit when the page changes...
But yeah it would be nice if this module could automatically change the src to `""` when the component unmounts... 
In the meantime I'm doing it my self - Thanks again!

**Comment by verlok** [comment]
Yea it would be. The problem is that “the component unmounts” is not a web standard (unless you use native web components), so it wouldn’t be a modification working everywhere.

**Comment by verlok** [comment]
Hey @jellohouse , 
I hope you solved your issue. 

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
