### ISSUE TITLE
data-bg retro compatibility

### ISSUE THREAD

**Issue by max4ever** [verlok/vanilla-lazyload#571]
**Is your feature request related to a problem? Please describe.**
Hi, the changes from version 14 to 15 are breaking, because not all of us can change the html we import from outside sources.

Do you think it is possible to add a config so that one can continue to have `data-bg="url(background.jpg)"`, I understand I can config the data-bg name, but can it still allow for `url()` ?

**Comment by verlok** [comment]
Hey @max4ever ,
thank you for opening this. 

I’ve just checked the file [UPGRADE.md](https://github.com/verlok/vanilla-lazyload/blob/master/UPGRADE.md) because I didn’t remember what I had changed then (it’s been quite some time ago). 

For what I’ve read there, you can still use `url()` inside the attribute if you use the `data-multi-bg` attribute instead of `data-bg`. 

It you can’t change the HTML, you could use LazyLoad options to map `data-bg` sto `data-multi-bg`. 

If you need an example, I’d be happy to provide it.

**Comment by verlok** [comment]
Hey @max4ever,
do you still need support?

**Comment by verlok** [comment]
Hey @max4ever,
I'm going to assume you solved by now.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
